POST http://localhost:8080/events/6/register
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3Q1QGV4YW1wbGUuY29tIiwiZXhwIjoxNzMwNDkyMjQxLCJ1c2VySWQiOjV9.qqAaIzGYeAYCxYDyYzIzQ99IwMMym2Gm9lPlFPYanfA